printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
quoteProps: consistent
trailingComma: all
bracketSpacing: true
arrowParens: always
overrides:
  - files: '*.md'
    options:
      printWidth: 9999
