settings:
  commonmark: true
  emphasis: '_'
  strong: '*'
  bullet: '-'
  incrementListMarker: true
  listItemIndent: one
  fences: true
  rule: '-'
plugins:
  - remark-prettier
  - remark-preset-lint-recommended
  - remark-frontmatter
  - - remark-lint-emphasis-marker
  - - remark-lint-strong-marker
  - - remark-lint-unordered-list-marker-style
    - '-'
  - - remark-lint-ordered-list-marker-value
    - ordered
  - - remark-lint-code-block-style
    - fenced
  - - remark-lint-list-item-indent
    - false
  - - '@mavrin/remark-typograf'
    - locale:
        - en-US
        - uk
      disableRule:
        - 'common/nbsp/*'
        - 'common/space/*'
